jobs:
  build:
    docker:
      - image: python:3.6                   # similar to "image" in GitLab
    steps:
      - checkout
      - run: |                              # similar to "script" in GitLab
          pip install -r requirements.txt
          python manage.py check

  test:
    needs:
      - build
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: |
          pip install -r requirements.txt
          python manage.py test taskManager

  integration:
    needs:
      - test
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          command: |
            echo "This is an integration step"
            exit 1
    allow_failure: true

  prod:
    needs:
      - integration
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: echo "This is a deploy step"

  artifact:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: |
          echo "hello" > hello.txt
    outputs:
      - name: artifact
        path: hello.txt

workflows:
  version: 2
  django:
    jobs:
      - build
      - test
      - integration
      - prod
      - artifact
    on:
      push:
        branches:
          - main
